### ISSUE TITLE
MUFlash bei https "SSL" kein Flash

### ISSUE THREAD

**Issue by Alexalter** [Portugao/MUFlash#4]
Hi,

MUFlash modul zeigt kein Flash bei https "SSL", gibst ein Lösung oder was zu ändern :-? 
sehe bitte auch hier https://al-werner.de/muflash/movie/id.11.html zeigt sowas "Für diese Webseite ist der Flashplayer mit der Version oder höher notwendig".

SSL Umleitung über htaccess,  StartCom Ltd
Zikula 1.3.9 Host All-Ink.com

Schöne Grüße
Alex

**Comment by Portugao** [comment]
@Alexalter 
Should be fixed. Please check actual repository.

**Comment by Alexalter** [comment]
Hi Portugao,
aber wo Server oder wie? kein SSH oder so was GIT auf Hosting all-inkl PriwatPlus :cry:

**Comment by Portugao** [comment]
Nutze auf der Hauptseite von MUFlash (https://github.com/Portugao/MUFlash) den 'Link Download Zip', um die aktuelle Version herunter zu laden.

**Comment by Alexalter** [comment]
ist drin

**Comment by Portugao** [comment]
:+1:

**Comment by Alexalter** [comment]
aber Flash immer noch nicht angezeigt :cry:

**Comment by Portugao** [comment]
Ich weiss nicht, woran es liegt; die Kommunikation zwischen uns ist nicht optimal. 
Woran liegt das? Sollten wir uns besser in englisch austauschen?

**Comment by Alexalter** [comment]
ich denke habe ich genug erzählt warum es geht.

**Comment by Guite** [comment]
FireBug zeigt, wo das Problem liegt:

Laden von gemischten aktiven Inhalten "http://al-werner.de/userdata/MUFlash/movies/flashfile/swfobject.js" wurde blockiert.

**Comment by Portugao** [comment]
@Alexalter 
Nun ist meine Verwirrung komplett.

Wieso schließt du den Issue. Geht es jetzt doch mit https?

@Guite
Yo, das habe ich schon ermittelt.

**Comment by Alexalter** [comment]
Geht doch :+1: 
Danke euch

**Comment by Portugao** [comment]
Fine! :+1: 
So i close this issue.

**Comment by Alexalter** [comment]
Problem ist noch offen. Muss mann noch was ändern in MUFlash Modul, Fehler korrigieren oder so was

**Comment by Portugao** [comment]
Oh mann....

**Comment by Portugao** [comment]
Ich steige nicht mehr durch
Geht doch, dann wieder Problem ist noch offen....

**Comment by Alexalter** [comment]
Ist ok mach ich selbe

**Comment by Alexalter** [comment]
ich habe doch Tema geschlossen

**Comment by Alexalter** [comment]
und geht doch Fehler aus suchen

**Comment by Portugao** [comment]
Mein Interesse ist, einen Fehler, der gemeldet wird, auch zu beheben!

Ich verstehe Deine Aussage nicht:
"und geht doch Fehler aus suchen "
Was willst Du damit sagen?

**Comment by Alexalter** [comment]
Vergiss es

**Comment by Portugao** [comment]
Nein! ich werde, es nicht vergessen.
Warun beantwortest Du meine Frage nicht? Ich möchte Dich gerne verstehen und den Fehler für alle Nutzer beheben. Dafür bin auch auf Deine Informationen angewiesen, da ich keine Testumgebung mit https habe.

**Comment by Alexalter** [comment]
Oh mann....

**Comment by Alexalter** [comment]
modules\MUFlash\lib\MUFlash\Entity\Movie.php in Zeile 78 und 79 "http://" umbenennen "https://" bei SSL

**Comment by Portugao** [comment]
Yo, danke.
Kannst Du bitte ausprobieren, ob es damit in Zeile 78 und 79 auch funktioniert?
```
    	$url = $host . '/userdata/MUFlash/movies/flashfile';
    	$url2 = $host . '/userdata/MUFlash/movies/flashfile/' . $flashfile;
```

**Comment by Alexalter** [comment]
leider nicht funktioniert in Zeile 78 und 79.
aber funktioniert auch so in Zeile 78 und 79 :tada: 

		$url = 'userdata/MUFlash/movies/flashfile';
    	$url2 = '/userdata/MUFlash/movies/flashfile/' . $flashfile;

**Comment by Portugao** [comment]
Danke; ist in die nächste Version 1.1.0 des Moduls eingearbeitet.
